### ISSUE TITLE
请问是否支持下载某个时间段？

### ISSUE THREAD

**Issue by weitieda** [WillieWangWei/WLM3U#1]
大佬好，

想请问下：比如整个视频20分钟，现在想下载 11:00 - 11:30 （不想下载全部），是否可以传个 start/end 区间进去只下载这个区间？

谢谢大佬

**Comment by WillieWangWei** [comment]
可以的。只需要在下载时，只下载时间段对应的切片就可以了。

但是，暂时没实现的这个功能，你可以按照这个思路简单实现一下。
