### ISSUE TITLE
点击下载，无法完成下载操作

### ISSUE THREAD

**Issue by LHWen** [WillieWangWei/WLM3U#3]
使用的是你提供的demo，更换换可播放的URL，点击下载：
attach failure The operation couldn’t be completed. (WLM3U.WLError error 0.)

![image](https://user-images.githubusercontent.com/15641889/80910083-ba95a400-8d5f-11ea-894e-b2dfa9176de2.png)

**Comment by WillieWangWei** [comment]
已更新 0.1.4 版本，修复相关问题。
