### ISSUE TITLE
demo m3u8下载失败 [Attach Failure] 操作缓存失败，请检查本地缓存是否正确。

### ISSUE THREAD

**Issue by Hext123** [WillieWangWei/WLM3U#4]
let url1 = "https://youku.com-t-youku.com/20190329/11010_06976355/index.m3u8"
        let url2 = "https://youku.cdn2-youku.com/20180707/12986_0929b432/index.m3u8"

**Comment by WillieWangWei** [comment]
这两个 URL 实际对应的文件 URL 是：

> https://youku.com-t-youku.com/20190329/11010_06976355/1000k/hls/index.m3u8

> https://youku.cdn2-youku.com/20180707/12986_0929b432/1000k/hls/index.m3u8

你可以直接使用这两个 URL 下载试试看。

**Comment by Hext123** [comment]
感谢解答.
这两个可以下载, 不过接口返回是视频就是那个m3u8, 那就只有先自己解析拿到下一层m3u8地址了~

还有就是, 下载时点击 "pause" 会抛出异常:
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “b2b425190a5000046.ts” couldn’t be opened because there is no such file." UserInfo={NSFilePath=~/Library/Developer/CoreSimulator/Devices/C4C211A9-9CDD-443B-9CB7-F02E8E3E45DB/data/Containers/Data/Application/C94A6D12-67FA-44C6-89C7-0E67840C5F6A/Documents/WLM3U/index/ts/b2b425190a5000046.ts, NSUnderlyingError=0x600003ff7fc0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file ~/Downloads/WLM3U-master/Sources/Workflow.swift, line 459

**Comment by WillieWangWei** [comment]
好的，WLM3U 暂不支持解析后重定向，所以需要业务先处理一下。

抛出异常的问题我会尽快处理，谢谢反馈～
