### ISSUE TITLE
The Progress and Completion don't match

### ISSUE THREAD

**Issue by deibytb** [WillieWangWei/WLM3U#5]
I have an error in:
`workflow.download(progress: <#T##DownloadProgress?##DownloadProgress?##(Progress, Int) -> ()#>, completion: <#T##DownloadCompletion?##DownloadCompletion?##(Result<URL>) -> ()#>)
`
when complete download, the progress is 5%

**Comment by WillieWangWei** [comment]
Can you give me your URL? let me try
