### ISSUE TITLE
OC代码如何使用啊？？？？给个建议啊

### ISSUE THREAD

**Issue by TinyMAX** [WillieWangWei/WLM3U#6]
OC代码如何使用啊？？？？给个建议啊

**Comment by WillieWangWei** [comment]
建议创建一个 Swift 类，封装 WLM3U 的接口给业务调用。需要注意的是，为了能让 OC 代码调用，新的接口要屏蔽掉 Swift 特有的类型或语法。

WLM3U --> **Bridge(Swift) --> @objc API** --> OC

**Comment by TinyMAX** [comment]
遇到另一个问题。我调用 cancel 暂停任务后，再调用attach重新开始下载，控制台输入：[Attach Success] 30062020166，但是没有继续下载了，回调没有响应

**Comment by TinyMAX** [comment]
这是返回的错误，请求超时：Task <B9247B7C-F74B-4320-AB5E-0EBF782DAF91>.<10> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x600003b06970 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <B9247B7C-F74B-4320-AB5E-0EBF782DAF91>.<10>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <B9247B7C-F74B-4320-AB5E-0EBF782DAF91>.<10>"

**Comment by WillieWangWei** [comment]
把 URL 发一下
